language: minimal
before_script:
    - export VERSION=${TRAVIS_BRANCH}  BUILDNUM=${TRAVIS_BUILD_NUMBER}
script:
    - docker-compose -f docker-compose.test.yml up --build --abort-on-container-exit
before_deploy:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
deploy:
    -
        provider: script
        script: docker push linksmart/hds:latest
        on:
            branch: master
            repo: linksmart/historical-datastore
    -
        provider: script
        script: docker tag linksmart/hds linksmart/hds:${TRAVIS_TAG} &&
            docker push linksmart/hds:${TRAVIS_TAG}
        on:
            tags: true
            repo: linksmart/historical-datastore
