# Dockerfile for Bamboo plans
FROM alpine

ARG VERSION
ARG BUILD
LABEL NAME="LinkSmart® Historical Datastore"
LABEL CODENAME="HDS"
LABEL VERSION=${VERSION}
LABEL BUILD=${BUILD}

RUN apk --no-cache add ca-certificates

COPY sample_conf/docker.json /conf/
COPY historical-datastore-linux-amd64 /home/historical-datastore

WORKDIR /home
RUN chmod +x historical-datastore

VOLUME /conf /data
EXPOSE 8085

ENTRYPOINT ["./historical-datastore"]
CMD ["-conf", "/conf/docker.json"]