// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

package _go

import (
	fmt "fmt"
	_ "github.com/farshidtz/senml-protobuf/go"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//The denormalization mask sp
type DenormMask int32

const (
	//No value is denormalized
	DenormMask_None   DenormMask = 0
	DenormMask_FName  DenormMask = 1
	DenormMask_FTime  DenormMask = 2
	DenormMask_FUnit  DenormMask = 4
	DenormMask_FValue DenormMask = 8
	DenormMask_FSum   DenormMask = 16
)

var DenormMask_name = map[int32]string{
	0:  "None",
	1:  "FName",
	2:  "FTime",
	4:  "FUnit",
	8:  "FValue",
	16: "FSum",
}

var DenormMask_value = map[string]int32{
	"None":   0,
	"FName":  1,
	"FTime":  2,
	"FUnit":  4,
	"FValue": 8,
	"FSum":   16,
}

func (x DenormMask) String() string {
	return proto.EnumName(DenormMask_name, int32(x))
}

func (DenormMask) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{0}
}

type Void struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Void) Reset()         { *m = Void{} }
func (m *Void) String() string { return proto.CompactTextString(m) }
func (*Void) ProtoMessage()    {}
func (*Void) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{0}
}

func (m *Void) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Void.Unmarshal(m, b)
}
func (m *Void) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Void.Marshal(b, m, deterministic)
}
func (m *Void) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Void.Merge(m, src)
}
func (m *Void) XXX_Size() int {
	return xxx_messageInfo_Void.Size(m)
}
func (m *Void) XXX_DiscardUnknown() {
	xxx_messageInfo_Void.DiscardUnknown(m)
}

var xxx_messageInfo_Void proto.InternalMessageInfo

type QueryRequest struct {
	Streams              []string   `protobuf:"bytes,1,rep,name=streams,proto3" json:"streams,omitempty"`
	From                 string     `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To                   string     `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	RecordPerPacket      int32      `protobuf:"varint,5,opt,name=recordPerPacket,proto3" json:"recordPerPacket,omitempty"`
	DenormaMask          DenormMask `protobuf:"varint,6,opt,name=denormaMask,proto3,enum=data.DenormMask" json:"denormaMask,omitempty"`
	SortAsc              bool       `protobuf:"varint,7,opt,name=sort_asc,json=sortAsc,proto3" json:"sort_asc,omitempty"`
	Limit                int32      `protobuf:"varint,8,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset               int32      `protobuf:"varint,9,opt,name=offset,proto3" json:"offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *QueryRequest) Reset()         { *m = QueryRequest{} }
func (m *QueryRequest) String() string { return proto.CompactTextString(m) }
func (*QueryRequest) ProtoMessage()    {}
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{1}
}

func (m *QueryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryRequest.Unmarshal(m, b)
}
func (m *QueryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryRequest.Marshal(b, m, deterministic)
}
func (m *QueryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRequest.Merge(m, src)
}
func (m *QueryRequest) XXX_Size() int {
	return xxx_messageInfo_QueryRequest.Size(m)
}
func (m *QueryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRequest proto.InternalMessageInfo

func (m *QueryRequest) GetStreams() []string {
	if m != nil {
		return m.Streams
	}
	return nil
}

func (m *QueryRequest) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *QueryRequest) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *QueryRequest) GetRecordPerPacket() int32 {
	if m != nil {
		return m.RecordPerPacket
	}
	return 0
}

func (m *QueryRequest) GetDenormaMask() DenormMask {
	if m != nil {
		return m.DenormaMask
	}
	return DenormMask_None
}

func (m *QueryRequest) GetSortAsc() bool {
	if m != nil {
		return m.SortAsc
	}
	return false
}

func (m *QueryRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *QueryRequest) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

type DeleteRequest struct {
	From                 string   `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To                   string   `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRequest) Reset()         { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()    {}
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{2}
}

func (m *DeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRequest.Unmarshal(m, b)
}
func (m *DeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRequest.Marshal(b, m, deterministic)
}
func (m *DeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRequest.Merge(m, src)
}
func (m *DeleteRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRequest.Size(m)
}
func (m *DeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRequest proto.InternalMessageInfo

func (m *DeleteRequest) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *DeleteRequest) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

type CountResponse struct {
	Total                int32    `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CountResponse) Reset()         { *m = CountResponse{} }
func (m *CountResponse) String() string { return proto.CompactTextString(m) }
func (*CountResponse) ProtoMessage()    {}
func (*CountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{3}
}

func (m *CountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CountResponse.Unmarshal(m, b)
}
func (m *CountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CountResponse.Marshal(b, m, deterministic)
}
func (m *CountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CountResponse.Merge(m, src)
}
func (m *CountResponse) XXX_Size() int {
	return xxx_messageInfo_CountResponse.Size(m)
}
func (m *CountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CountResponse proto.InternalMessageInfo

func (m *CountResponse) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func init() {
	proto.RegisterEnum("data.DenormMask", DenormMask_name, DenormMask_value)
	proto.RegisterType((*Void)(nil), "data.Void")
	proto.RegisterType((*QueryRequest)(nil), "data.QueryRequest")
	proto.RegisterType((*DeleteRequest)(nil), "data.DeleteRequest")
	proto.RegisterType((*CountResponse)(nil), "data.CountResponse")
}

func init() {
	proto.RegisterFile("service.proto", fileDescriptor_a0b84a42fa06f626)
}

var fileDescriptor_a0b84a42fa06f626 = []byte{
	// 453 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x51, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0xce, 0xa6, 0xb6, 0x93, 0x4c, 0x49, 0xb1, 0xa6, 0x08, 0x4c, 0x4e, 0x96, 0x25, 0x24, 0x0b,
	0x84, 0x8d, 0x52, 0x21, 0xb8, 0x02, 0x51, 0x6e, 0xa9, 0x8a, 0x0b, 0x3d, 0x70, 0xa9, 0x36, 0xce,
	0x24, 0x5d, 0xc5, 0xeb, 0x2d, 0xbb, 0x6b, 0x24, 0x5e, 0x93, 0x57, 0xe1, 0x05, 0x90, 0xd7, 0x58,
	0xa4, 0x40, 0x6f, 0xf3, 0x7d, 0xde, 0xf1, 0x7c, 0x3f, 0x30, 0x35, 0xa4, 0xbf, 0x89, 0x92, 0xb2,
	0x5b, 0xad, 0xac, 0x42, 0x6f, 0xc3, 0x2d, 0x9f, 0x1d, 0x1b, 0xaa, 0x65, 0xd5, 0x51, 0x49, 0x00,
	0xde, 0x95, 0x12, 0x9b, 0xe4, 0x27, 0x83, 0x07, 0x1f, 0x1b, 0xd2, 0xdf, 0x0b, 0xfa, 0xda, 0x90,
	0xb1, 0x18, 0xc1, 0xc8, 0x58, 0x4d, 0x5c, 0x9a, 0x88, 0xc5, 0x47, 0xe9, 0xa4, 0xe8, 0x21, 0x22,
	0x78, 0x5b, 0xad, 0x64, 0x34, 0x8c, 0x59, 0x3a, 0x29, 0xdc, 0x8c, 0x27, 0x30, 0xb4, 0x2a, 0x3a,
	0x72, 0xcc, 0xd0, 0x2a, 0x4c, 0xe1, 0xa1, 0xa6, 0x52, 0xe9, 0xcd, 0x05, 0xe9, 0x0b, 0x5e, 0xee,
	0xc9, 0x46, 0x7e, 0xcc, 0x52, 0xbf, 0xf8, 0x9b, 0xc6, 0x39, 0x1c, 0x6f, 0xa8, 0x56, 0x5a, 0xf2,
	0x15, 0x37, 0xfb, 0x28, 0x88, 0x59, 0x7a, 0x32, 0x0f, 0xb3, 0x56, 0x69, 0xb6, 0x70, 0x1f, 0x5a,
	0xbe, 0x38, 0x7c, 0x84, 0x4f, 0x61, 0x6c, 0x94, 0xb6, 0xd7, 0xdc, 0x94, 0xd1, 0x28, 0x66, 0xe9,
	0xb8, 0x18, 0xb5, 0xf8, 0x9d, 0x29, 0xf1, 0x11, 0xf8, 0x95, 0x90, 0xc2, 0x46, 0x63, 0x77, 0xae,
	0x03, 0xf8, 0x18, 0x02, 0xb5, 0xdd, 0x1a, 0xb2, 0xd1, 0xc4, 0xd1, 0xbf, 0x51, 0x72, 0x06, 0xd3,
	0x05, 0x55, 0x64, 0xa9, 0x77, 0xdd, 0x7b, 0x63, 0xff, 0x78, 0x1b, 0xf6, 0xde, 0x92, 0x67, 0x30,
	0xfd, 0xa0, 0x9a, 0xda, 0x16, 0x64, 0x6e, 0x55, 0x6d, 0xa8, 0xbd, 0x69, 0x95, 0xe5, 0x95, 0xdb,
	0xf2, 0x8b, 0x0e, 0x3c, 0x5f, 0x01, 0xfc, 0xd1, 0x8f, 0x63, 0xf0, 0xce, 0x55, 0x4d, 0xe1, 0x00,
	0x27, 0xe0, 0x2f, 0xcf, 0xb9, 0xa4, 0x90, 0xb9, 0xf1, 0x93, 0x90, 0x14, 0x0e, 0xdd, 0xf8, 0xb9,
	0x16, 0x36, 0xf4, 0x10, 0x20, 0x58, 0x5e, 0xf1, 0xaa, 0xa1, 0x70, 0xdc, 0xae, 0x2d, 0x2f, 0x1b,
	0x19, 0x86, 0xf3, 0x1f, 0x0c, 0xbc, 0x05, 0xb7, 0x1c, 0x73, 0x08, 0x2e, 0x9b, 0x75, 0xeb, 0xea,
	0x49, 0xe6, 0x9a, 0xbc, 0x76, 0x4d, 0xae, 0x9b, 0x6d, 0xb6, 0x22, 0x63, 0xf8, 0x8e, 0x66, 0xd0,
	0xc5, 0xe7, 0x8a, 0x1d, 0xe0, 0x5b, 0xf0, 0x5d, 0xb3, 0x88, 0x1d, 0x7d, 0x58, 0xf3, 0xec, 0xbe,
	0x7f, 0x24, 0x83, 0x57, 0x0c, 0xe7, 0xe0, 0x3b, 0xa7, 0xff, 0xdd, 0x3c, 0xed, 0xb8, 0x3b, 0x51,
	0x24, 0x03, 0x7c, 0x01, 0x41, 0x17, 0x29, 0x9e, 0xf6, 0x25, 0x1e, 0x04, 0x7c, 0x57, 0xda, 0xfb,
	0x37, 0x5f, 0x5e, 0xef, 0x84, 0xbd, 0x69, 0xd6, 0x59, 0xa9, 0x64, 0x5e, 0x89, 0x7a, 0x6f, 0x24,
	0xd7, 0x36, 0xbf, 0x11, 0xc6, 0x2a, 0x2d, 0x4a, 0x5e, 0xbd, 0x6c, 0x9f, 0xb7, 0x80, 0xf2, 0x5e,
	0x62, 0xbe, 0x53, 0xeb, 0xc0, 0x81, 0xb3, 0x5f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xd1, 0x00, 0x70,
	0x90, 0xe1, 0x02, 0x00, 0x00,
}
