// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

package _go

import (
	context "context"
	fmt "fmt"
	_go "github.com/farshidtz/senml-protobuf/go"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//The denormalization mask sp
type DenormMask int32

const (
	//No value is denormalized
	DenormMask_None   DenormMask = 0
	DenormMask_FName  DenormMask = 1
	DenormMask_FTime  DenormMask = 2
	DenormMask_FUnit  DenormMask = 4
	DenormMask_FValue DenormMask = 8
	DenormMask_FSum   DenormMask = 16
)

var DenormMask_name = map[int32]string{
	0:  "None",
	1:  "FName",
	2:  "FTime",
	4:  "FUnit",
	8:  "FValue",
	16: "FSum",
}

var DenormMask_value = map[string]int32{
	"None":   0,
	"FName":  1,
	"FTime":  2,
	"FUnit":  4,
	"FValue": 8,
	"FSum":   16,
}

func (x DenormMask) String() string {
	return proto.EnumName(DenormMask_name, int32(x))
}

func (DenormMask) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{0}
}

type Void struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Void) Reset()         { *m = Void{} }
func (m *Void) String() string { return proto.CompactTextString(m) }
func (*Void) ProtoMessage()    {}
func (*Void) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{0}
}

func (m *Void) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Void.Unmarshal(m, b)
}
func (m *Void) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Void.Marshal(b, m, deterministic)
}
func (m *Void) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Void.Merge(m, src)
}
func (m *Void) XXX_Size() int {
	return xxx_messageInfo_Void.Size(m)
}
func (m *Void) XXX_DiscardUnknown() {
	xxx_messageInfo_Void.DiscardUnknown(m)
}

var xxx_messageInfo_Void proto.InternalMessageInfo

type QueryRequest struct {
	Streams              []string   `protobuf:"bytes,1,rep,name=streams,proto3" json:"streams,omitempty"`
	From                 string     `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To                   string     `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	RecordPerPacket      int32      `protobuf:"varint,5,opt,name=recordPerPacket,proto3" json:"recordPerPacket,omitempty"`
	DenormaMask          DenormMask `protobuf:"varint,6,opt,name=denormaMask,proto3,enum=data.DenormMask" json:"denormaMask,omitempty"`
	SortAsc              bool       `protobuf:"varint,7,opt,name=sort_asc,json=sortAsc,proto3" json:"sort_asc,omitempty"`
	Limit                int32      `protobuf:"varint,8,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset               int32      `protobuf:"varint,9,opt,name=offset,proto3" json:"offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *QueryRequest) Reset()         { *m = QueryRequest{} }
func (m *QueryRequest) String() string { return proto.CompactTextString(m) }
func (*QueryRequest) ProtoMessage()    {}
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{1}
}

func (m *QueryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryRequest.Unmarshal(m, b)
}
func (m *QueryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryRequest.Marshal(b, m, deterministic)
}
func (m *QueryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRequest.Merge(m, src)
}
func (m *QueryRequest) XXX_Size() int {
	return xxx_messageInfo_QueryRequest.Size(m)
}
func (m *QueryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRequest proto.InternalMessageInfo

func (m *QueryRequest) GetStreams() []string {
	if m != nil {
		return m.Streams
	}
	return nil
}

func (m *QueryRequest) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *QueryRequest) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *QueryRequest) GetRecordPerPacket() int32 {
	if m != nil {
		return m.RecordPerPacket
	}
	return 0
}

func (m *QueryRequest) GetDenormaMask() DenormMask {
	if m != nil {
		return m.DenormaMask
	}
	return DenormMask_None
}

func (m *QueryRequest) GetSortAsc() bool {
	if m != nil {
		return m.SortAsc
	}
	return false
}

func (m *QueryRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *QueryRequest) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

type DeleteRequest struct {
	Streams              []string `protobuf:"bytes,1,rep,name=streams,proto3" json:"streams,omitempty"`
	From                 string   `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To                   string   `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRequest) Reset()         { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()    {}
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{2}
}

func (m *DeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRequest.Unmarshal(m, b)
}
func (m *DeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRequest.Marshal(b, m, deterministic)
}
func (m *DeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRequest.Merge(m, src)
}
func (m *DeleteRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRequest.Size(m)
}
func (m *DeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRequest proto.InternalMessageInfo

func (m *DeleteRequest) GetStreams() []string {
	if m != nil {
		return m.Streams
	}
	return nil
}

func (m *DeleteRequest) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *DeleteRequest) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

type CountResponse struct {
	Total                int32    `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CountResponse) Reset()         { *m = CountResponse{} }
func (m *CountResponse) String() string { return proto.CompactTextString(m) }
func (*CountResponse) ProtoMessage()    {}
func (*CountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{3}
}

func (m *CountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CountResponse.Unmarshal(m, b)
}
func (m *CountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CountResponse.Marshal(b, m, deterministic)
}
func (m *CountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CountResponse.Merge(m, src)
}
func (m *CountResponse) XXX_Size() int {
	return xxx_messageInfo_CountResponse.Size(m)
}
func (m *CountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CountResponse proto.InternalMessageInfo

func (m *CountResponse) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func init() {
	proto.RegisterEnum("data.DenormMask", DenormMask_name, DenormMask_value)
	proto.RegisterType((*Void)(nil), "data.Void")
	proto.RegisterType((*QueryRequest)(nil), "data.QueryRequest")
	proto.RegisterType((*DeleteRequest)(nil), "data.DeleteRequest")
	proto.RegisterType((*CountResponse)(nil), "data.CountResponse")
}

func init() {
	proto.RegisterFile("service.proto", fileDescriptor_a0b84a42fa06f626)
}

var fileDescriptor_a0b84a42fa06f626 = []byte{
	// 448 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x52, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0xce, 0xa6, 0xb6, 0x9b, 0x4c, 0x49, 0xb1, 0xa6, 0x08, 0x96, 0x9c, 0x2c, 0x4b, 0x48, 0x16,
	0x08, 0x1b, 0x05, 0x21, 0xb8, 0x02, 0x51, 0x6e, 0xa9, 0x8a, 0x0b, 0x3d, 0x70, 0xa9, 0x36, 0xce,
	0x24, 0x5d, 0xc5, 0xeb, 0x2d, 0xbb, 0x6b, 0x24, 0x5e, 0x93, 0x57, 0xe1, 0x05, 0x90, 0xd7, 0x44,
	0xa4, 0x08, 0x6e, 0xdc, 0xe6, 0xfb, 0x3c, 0x63, 0x7f, 0x3f, 0x86, 0x89, 0x25, 0xf3, 0x55, 0x56,
	0x94, 0xdf, 0x1a, 0xed, 0x34, 0x06, 0x6b, 0xe1, 0xc4, 0xf4, 0xc4, 0x52, 0xa3, 0xea, 0x9e, 0x4a,
	0x23, 0x08, 0xae, 0xb4, 0x5c, 0xa7, 0x3f, 0x18, 0xdc, 0xfb, 0xd0, 0x92, 0xf9, 0x56, 0xd2, 0x97,
	0x96, 0xac, 0x43, 0x0e, 0xc7, 0xd6, 0x19, 0x12, 0xca, 0x72, 0x96, 0x1c, 0x65, 0xe3, 0x72, 0x0f,
	0x11, 0x21, 0xd8, 0x18, 0xad, 0xf8, 0x30, 0x61, 0xd9, 0xb8, 0xf4, 0x33, 0x9e, 0xc2, 0xd0, 0x69,
	0x7e, 0xe4, 0x99, 0xa1, 0xd3, 0x98, 0xc1, 0x7d, 0x43, 0x95, 0x36, 0xeb, 0x0b, 0x32, 0x17, 0xa2,
	0xda, 0x91, 0xe3, 0x61, 0xc2, 0xb2, 0xb0, 0xfc, 0x93, 0xc6, 0x19, 0x9c, 0xac, 0xa9, 0xd1, 0x46,
	0x89, 0xa5, 0xb0, 0x3b, 0x1e, 0x25, 0x2c, 0x3b, 0x9d, 0xc5, 0x79, 0xa7, 0x34, 0x9f, 0xfb, 0x07,
	0x1d, 0x5f, 0x1e, 0x2e, 0xe1, 0x63, 0x18, 0x59, 0x6d, 0xdc, 0xb5, 0xb0, 0x15, 0x3f, 0x4e, 0x58,
	0x36, 0x2a, 0x8f, 0x3b, 0xfc, 0xd6, 0x56, 0xf8, 0x00, 0xc2, 0x5a, 0x2a, 0xe9, 0xf8, 0xc8, 0x7f,
	0xae, 0x07, 0xf8, 0x10, 0x22, 0xbd, 0xd9, 0x58, 0x72, 0x7c, 0xec, 0xe9, 0x5f, 0x28, 0x5d, 0xc2,
	0x64, 0x4e, 0x35, 0x39, 0xfa, 0x2f, 0xae, 0xd3, 0x27, 0x30, 0x79, 0xaf, 0xdb, 0xc6, 0x95, 0x64,
	0x6f, 0x75, 0x63, 0xa9, 0x53, 0xe3, 0xb4, 0x13, 0x35, 0x67, 0xbd, 0x1a, 0x0f, 0x9e, 0x2e, 0x01,
	0x7e, 0x3b, 0xc3, 0x11, 0x04, 0xe7, 0xba, 0xa1, 0x78, 0x80, 0x63, 0x08, 0x17, 0xe7, 0x42, 0x51,
	0xcc, 0xfc, 0xf8, 0x51, 0x2a, 0x8a, 0x87, 0x7e, 0xfc, 0xd4, 0x48, 0x17, 0x07, 0x08, 0x10, 0x2d,
	0xae, 0x44, 0xdd, 0x52, 0x3c, 0xea, 0xce, 0x16, 0x97, 0xad, 0x8a, 0xe3, 0xd9, 0x77, 0x06, 0xc1,
	0x5c, 0x38, 0x81, 0x05, 0x44, 0x97, 0xed, 0xaa, 0xf3, 0xfb, 0x28, 0xf7, 0x1d, 0x5f, 0xfb, 0x8e,
	0x57, 0xed, 0x26, 0x5f, 0x92, 0xb5, 0x62, 0x4b, 0x53, 0xe8, 0x83, 0xf5, 0x95, 0x0f, 0xf0, 0x0d,
	0x84, 0xbe, 0x73, 0xc4, 0x9e, 0x3e, 0xfc, 0x01, 0xa6, 0xff, 0x7a, 0x47, 0x3a, 0x78, 0xc1, 0x70,
	0x06, 0xa1, 0x77, 0xfa, 0xd7, 0xcb, 0xb3, 0x9e, 0xbb, 0x13, 0x45, 0x3a, 0xc0, 0x67, 0x10, 0xf5,
	0x61, 0xe3, 0xd9, 0xbe, 0xde, 0x83, 0xe8, 0xef, 0x4a, 0x7b, 0xf7, 0xfa, 0xf3, 0xab, 0xad, 0x74,
	0x37, 0xed, 0x2a, 0xaf, 0xb4, 0x2a, 0x6a, 0xd9, 0xec, 0xac, 0x12, 0xc6, 0x15, 0x37, 0xd2, 0x3a,
	0x6d, 0x64, 0x25, 0xea, 0xe7, 0xdd, 0x7a, 0x07, 0xa8, 0xd8, 0x4b, 0x2c, 0xb6, 0x7a, 0x15, 0x79,
	0xf0, 0xf2, 0x67, 0x00, 0x00, 0x00, 0xff, 0xff, 0x6e, 0xc1, 0xf9, 0x54, 0xfb, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// DataClient is the client API for Data service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DataClient interface {
	Submit(ctx context.Context, in *_go.Message, opts ...grpc.CallOption) (*Void, error)
	Query(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (Data_QueryClient, error)
	Count(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*CountResponse, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*Void, error)
}

type dataClient struct {
	cc grpc.ClientConnInterface
}

func NewDataClient(cc grpc.ClientConnInterface) DataClient {
	return &dataClient{cc}
}

func (c *dataClient) Submit(ctx context.Context, in *_go.Message, opts ...grpc.CallOption) (*Void, error) {
	out := new(Void)
	err := c.cc.Invoke(ctx, "/data.Data/Submit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataClient) Query(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (Data_QueryClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Data_serviceDesc.Streams[0], "/data.Data/Query", opts...)
	if err != nil {
		return nil, err
	}
	x := &dataQueryClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Data_QueryClient interface {
	Recv() (*_go.Message, error)
	grpc.ClientStream
}

type dataQueryClient struct {
	grpc.ClientStream
}

func (x *dataQueryClient) Recv() (*_go.Message, error) {
	m := new(_go.Message)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *dataClient) Count(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*CountResponse, error) {
	out := new(CountResponse)
	err := c.cc.Invoke(ctx, "/data.Data/Count", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*Void, error) {
	out := new(Void)
	err := c.cc.Invoke(ctx, "/data.Data/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DataServer is the server API for Data service.
type DataServer interface {
	Submit(context.Context, *_go.Message) (*Void, error)
	Query(*QueryRequest, Data_QueryServer) error
	Count(context.Context, *QueryRequest) (*CountResponse, error)
	Delete(context.Context, *DeleteRequest) (*Void, error)
}

// UnimplementedDataServer can be embedded to have forward compatible implementations.
type UnimplementedDataServer struct {
}

func (*UnimplementedDataServer) Submit(ctx context.Context, req *_go.Message) (*Void, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Submit not implemented")
}
func (*UnimplementedDataServer) Query(req *QueryRequest, srv Data_QueryServer) error {
	return status.Errorf(codes.Unimplemented, "method Query not implemented")
}
func (*UnimplementedDataServer) Count(ctx context.Context, req *QueryRequest) (*CountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Count not implemented")
}
func (*UnimplementedDataServer) Delete(ctx context.Context, req *DeleteRequest) (*Void, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}

func RegisterDataServer(s *grpc.Server, srv DataServer) {
	s.RegisterService(&_Data_serviceDesc, srv)
}

func _Data_Submit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(_go.Message)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataServer).Submit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/data.Data/Submit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataServer).Submit(ctx, req.(*_go.Message))
	}
	return interceptor(ctx, in, info, handler)
}

func _Data_Query_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(QueryRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DataServer).Query(m, &dataQueryServer{stream})
}

type Data_QueryServer interface {
	Send(*_go.Message) error
	grpc.ServerStream
}

type dataQueryServer struct {
	grpc.ServerStream
}

func (x *dataQueryServer) Send(m *_go.Message) error {
	return x.ServerStream.SendMsg(m)
}

func _Data_Count_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataServer).Count(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/data.Data/Count",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataServer).Count(ctx, req.(*QueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Data_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/data.Data/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Data_serviceDesc = grpc.ServiceDesc{
	ServiceName: "data.Data",
	HandlerType: (*DataServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Submit",
			Handler:    _Data_Submit_Handler,
		},
		{
			MethodName: "Count",
			Handler:    _Data_Count_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Data_Delete_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Query",
			Handler:       _Data_Query_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "service.proto",
}
