on: [push, pull_request]
name: Docker test build and release
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: set build number and version
      run: export VERSION=${GITHUB_REF##*/}  BUILDNUM=${GITHUB_RUN_NUMBER}
      
    - name: Test code
      run: docker-compose -f docker-compose.test.yml up --build --abort-on-container-exit
       
    - name: Login to DockerHub Registry
      uses: Azure/docker-login@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
    - name: docker push latest
      run: docker push linksmart/hds:latest
      if: github.ref == 'refs/heads/master'
    
    - name: docker push tagged
      run: docker tag linksmart/hds linksmart/hds:${VERSION} && docker push linksmart/hds:${VERSION}
      if: startsWith(github.ref, 'refs/tags/') # on tag
